/**
 * Service Ticket Status Constants
 * Theo API mới
 */
export const SERVICE_TICKET_STATUS = {
	PENDING_TECHNICAL_CONFIRMATION: 0,
	ADJUSTED_BY_TECHNICAL: 1,
	IN_PROGRESS: 2,
	COMPLETED: 3,
	COMPLETED_PAYMENT: 5,
	CANCELLED: 4
}

export const SERVICE_TICKET_STATUS_LABELS = {
	[SERVICE_TICKET_STATUS.PENDING_TECHNICAL_CONFIRMATION]: 'Chờ xác nhận kỹ thuật',
	[SERVICE_TICKET_STATUS.ADJUSTED_BY_TECHNICAL]: 'Đã điều chỉnh',
	[SERVICE_TICKET_STATUS.IN_PROGRESS]: 'Đang xử lý',
	[SERVICE_TICKET_STATUS.COMPLETED]: 'Hoàn thành sửa chữa',
	[SERVICE_TICKET_STATUS.COMPLETED_PAYMENT]: 'Đã thanh toán',
	[SERVICE_TICKET_STATUS.CANCELLED]: 'Đã hủy'
}

export const SERVICE_TICKET_STATUS_COLORS = {
	[SERVICE_TICKET_STATUS.PENDING_TECHNICAL_CONFIRMATION]: 'info',
	[SERVICE_TICKET_STATUS.ADJUSTED_BY_TECHNICAL]: 'warning',
	[SERVICE_TICKET_STATUS.IN_PROGRESS]: 'primary',
	[SERVICE_TICKET_STATUS.COMPLETED]: 'success',
	[SERVICE_TICKET_STATUS.COMPLETED_PAYMENT]: 'success',
	[SERVICE_TICKET_STATUS.CANCELLED]: 'danger'
}

/**
 * Technical Task Status Constants
 */
export const TASK_STATUS = {
	PENDING: 0,
	IN_PROGRESS: 1,
	COMPLETED: 2
}

export const TASK_STATUS_LABELS = {
	[TASK_STATUS.PENDING]: 'Chờ bắt đầu',
	[TASK_STATUS.IN_PROGRESS]: 'Đang thực hiện',
	[TASK_STATUS.COMPLETED]: 'Hoàn thành'
}

export const TASK_STATUS_COLORS = {
	[TASK_STATUS.PENDING]: 'info',
	[TASK_STATUS.IN_PROGRESS]: 'warning',
	[TASK_STATUS.COMPLETED]: 'success'
}
